/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package deu.hms.roomManagement;

import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Jimin
 */
public class RoomManagementFrame extends javax.swing.JFrame {
    private RoomService roomService;
    
    public RoomManagementFrame() {
        initComponents();
    }

    public RoomManagementFrame(RoomService roomService) {
        this.roomService = roomService;
        initComponents();
        setLocationRelativeTo(null);
        roomService.getRoomRepository().loadRoomDataToTable(roomTable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roomManagement = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        roomTable = new javax.swing.JTable();
        saveButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        roomManagement.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        roomManagement.setText("객실 관리");

        roomTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "층", "호수", "가격", "등급", "인원"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        roomTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roomTableMouseClicked(evt);
            }
        });
        jScrollPane.setViewportView(roomTable);
        if (roomTable.getColumnModel().getColumnCount() > 0) {
            roomTable.getColumnModel().getColumn(0).setPreferredWidth(50);
            roomTable.getColumnModel().getColumn(3).setPreferredWidth(100);
        }

        saveButton.setText("저장");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("삭제");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        addButton.setText("등록");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        backButton.setText("<");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(backButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(roomManagement))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(addButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(deleteButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(saveButton))
                        .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(backButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(roomManagement)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(deleteButton)
                    .addComponent(addButton))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void roomTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomTableMouseClicked

    }//GEN-LAST:event_roomTableMouseClicked

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // 저장 버튼 클릭 시 RoomRepository를 이용하여 객실 정보를 파일에 저장
        roomService.getRoomRepository().saveRoomInfoToFile();
        JOptionPane.showMessageDialog(this, "객실 정보가 파일에 저장되었습니다.", "저장 성공", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_saveButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // 삭제 버튼 클릭 시 RoomService를 이용하여 객실 삭제 기능 호출
        String floorStr = JOptionPane.showInputDialog(this, "삭제할 객실의 층 번호를 입력하세요:");
        String roomNumberStr = JOptionPane.showInputDialog(this, "삭제할 객실의 방 번호를 입력하세요:");
        
        try {
            int floor = Integer.parseInt(floorStr.trim());
            int roomNumber = Integer.parseInt(roomNumberStr.trim());
            roomService.deleteRoom(floor, roomNumber);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "올바른 숫자를 입력해 주세요.", "입력 오류", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // 추가 버튼 클릭 시 RoomService를 이용하여 객실 추가 기능 호출
        String floorStr = JOptionPane.showInputDialog(this, "추가할 객실의 층 번호를 입력하세요:");
        String roomNumberStr = JOptionPane.showInputDialog(this, "추가할 객실의 방 번호를 입력하세요:");
        String priceStr = JOptionPane.showInputDialog(this, "객실의 가격을 입력하세요:");
        String grade = JOptionPane.showInputDialog(this, "객실의 등급을 입력하세요 (Standard, Deluxe, Suite):");
        String capacityStr = JOptionPane.showInputDialog(this, "객실의 수용 인원을 입력하세요:");
        
        try {
            int floor = Integer.parseInt(floorStr.trim());
            int roomNumber = Integer.parseInt(roomNumberStr.trim());
            int price = Integer.parseInt(priceStr.trim());
            int capacity = Integer.parseInt(capacityStr.trim());
            
            Room newRoom = new Room(floor, roomNumber, price, grade, capacity);
            roomService.addRoom(newRoom);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "올바른 숫자를 입력해 주세요.", "입력 오류", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        try {
            UIManager.setLookAndFeel("javax.swing.plaf.nimbus.NimbusLookAndFeel");
        } catch (Exception e) {
            e.printStackTrace();
        }
        RoomRepository roomRepository = new RoomRepository();
        RoomService roomService = new RoomService(roomRepository);
        RoomManagementFrame frame = new RoomManagementFrame(roomService);
        frame.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel roomManagement;
    private javax.swing.JTable roomTable;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
