/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package deu.hms.login;

/**
 *
 * @author yunhe
 */
public class MainScreenManager extends javax.swing.JFrame {
    
    private UserAuthentication auth;
    private Object deu;
    
    /**
     * Creates new form MainScreenManager
     */
    public MainScreenManager(UserAuthentication auth) {
        this.auth = auth;  // 로그인 인증 객체를 생성자로 전달받음
        initComponents();
    }
    
     @Override
    public void dispose() {
        super.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GoRestaurantManager = new javax.swing.JButton();
        GoReservationManager = new javax.swing.JButton();
        GoCheckinManager = new javax.swing.JButton();
        GocheckoutManager = new javax.swing.JButton();
        GoRoomserviceManager = new javax.swing.JButton();
        GoManagement = new javax.swing.JButton();
        GoReport = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        GoRestaurantManager.setText("레스토랑");
        GoRestaurantManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoRestaurantManagerActionPerformed(evt);
            }
        });

        GoReservationManager.setText("예약 관리");
        GoReservationManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoReservationManagerActionPerformed(evt);
            }
        });

        GoCheckinManager.setText("체크인");
        GoCheckinManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoCheckinManagerActionPerformed(evt);
            }
        });

        GocheckoutManager.setText("체크아웃");
        GocheckoutManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GocheckoutManagerActionPerformed(evt);
            }
        });

        GoRoomserviceManager.setText("룸서비스");
        GoRoomserviceManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoRoomserviceManagerActionPerformed(evt);
            }
        });

        GoManagement.setText("호텔 관리");
        GoManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoManagementActionPerformed(evt);
            }
        });

        GoReport.setText("보고서");
        GoReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoReportActionPerformed(evt);
            }
        });

        logoutButton.setText("out");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(GoReservationManager, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(GoRoomserviceManager, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(GoRestaurantManager, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(GoCheckinManager, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(GocheckoutManager, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(GoReport, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(GoManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GoReservationManager, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GoCheckinManager, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GocheckoutManager, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GoRoomserviceManager, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GoRestaurantManager, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GoManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GoReport, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GoRestaurantManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoRestaurantManagerActionPerformed
        deu.hms.restaurant.restaurantFrame restaurantFrame = new deu.hms.restaurant.restaurantFrame(new java.awt.Frame(), true);
        restaurantFrame.setLocationRelativeTo(null);  // 화면 가운데 배치
        restaurantFrame.setVisible(true);
        this.dispose();  // 현재 창 닫기
    }//GEN-LAST:event_GoRestaurantManagerActionPerformed

    private void GoReservationManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoReservationManagerActionPerformed
        deu.hms.reservation.reservationFrame reservationFrame = new deu.hms.reservation.reservationFrame(new java.awt.Frame(), true);
        reservationFrame.setLocationRelativeTo(null);  // 화면 가운데 배치
        reservationFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_GoReservationManagerActionPerformed

    private void GoCheckinManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoCheckinManagerActionPerformed
        deu.hms.checkin.checkIn checkinFrame = new deu.hms.checkin.checkIn(new java.awt.Frame(), true);
        checkinFrame.setLocationRelativeTo(null);  // 화면 가운데 배치
        checkinFrame.setVisible(true);
        this.dispose();  // 현재 창 닫기
    }//GEN-LAST:event_GoCheckinManagerActionPerformed

    private void GocheckoutManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GocheckoutManagerActionPerformed
        deu.hms.checkout.checkoutFrame checkoutFrame = new deu.hms.checkout.checkoutFrame(new java.awt.Frame(), true);
        checkoutFrame.setLocationRelativeTo(null);  // 화면 가운데 배치
        checkoutFrame.setVisible(true);
        this.dispose();  // 현재 창 닫기
    }//GEN-LAST:event_GocheckoutManagerActionPerformed

    private void GoRoomserviceManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoRoomserviceManagerActionPerformed
       //  deu.hms.roomservice.roomserviceFrame roomserviceFrame = new deu.hms.roomservice.roomserviceFrame(new java.awt.Frame(), true);
        //roomserviceFrame.setLocationRelativeTo(null);  // 화면 가운데 배치
        //roomserviceFrame.setVisible(true);
        this.dispose();  // 현재 창 닫기
    }//GEN-LAST:event_GoRoomserviceManagerActionPerformed

    private void GoManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoManagementActionPerformed
        // management 패키지 내 managementFrame을 생성하여 화면에 띄움
         deu.hms.management.managementFrame managementScreen = new deu.hms.management.managementFrame(this, true);
        managementScreen.setLocationRelativeTo(null); // 중앙에 띄우기
        managementScreen.setVisible(true); // 화면에 표시
        this.dispose(); // 현재 화면을 닫음 (이동 후 현재 화면을 숨기고 싶다면)
    }//GEN-LAST:event_GoManagementActionPerformed

    private void GoReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoReportActionPerformed
        // report 패키지 내 reportFrame을 생성하여 화면에 띄움
         deu.hms.report.reportFrame reportScreen = new deu.hms.report.reportFrame(this, true);
        reportScreen.setLocationRelativeTo(null); // 중앙에 띄우기
        reportScreen.setVisible(true); // 화면에 표시
        this.dispose(); // 현재 화면을 닫음 (이동 후 현재 화면을 숨기고 싶다면)
    }//GEN-LAST:event_GoReportActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // 로그아웃 처리
        auth.logout();  // UserAuthentication 객체에서 로그아웃 처리
        
        // MainScreenManager 창 닫기
        this.dispose();  // 현재 창 (MainScreenManager) 닫기
        
        // 로그인 창으로 돌아가기
        loginFrame loginScreen = new loginFrame(auth); // 로그인 화면 생성
        loginScreen.setLocationRelativeTo(null);  // 화면 중앙에 배치
        loginScreen.setVisible(true);  // 로그인 화면 표시
        
        
    }//GEN-LAST:event_logoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreenManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreenManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreenManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreenManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        // UserAuthentication 객체 생성 후 MainScreenManager 실행
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UserAuthentication auth = new UserAuthentication();  // UserAuthentication 객체 생성
                new MainScreenManager(auth).setVisible(true);  // 생성된 auth 객체를 전달
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GoCheckinManager;
    private javax.swing.JButton GoManagement;
    private javax.swing.JButton GoReport;
    private javax.swing.JButton GoReservationManager;
    private javax.swing.JButton GoRestaurantManager;
    private javax.swing.JButton GoRoomserviceManager;
    private javax.swing.JButton GocheckoutManager;
    private javax.swing.JButton logoutButton;
    // End of variables declaration//GEN-END:variables
}
