/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package deu.hms.checkin;

import deu.hms.reservation.ReservationData;
import deu.hms.utility.CardRegistFrame;
import deu.hms.utility.HotelRoomReservationUI;
import javax.swing.*;
import java.util.UUID;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Jimin
 */
public class GuestRegist extends JFrame {

    private ReservationManager reservationManager;
    public javax.swing.JTable reservationListTable;
    private CheckInUI checkInUI; // CheckInUI 클래스의 인스턴스를 참조하기 위한 필드 추가

    // 생성자에서 CheckInUI 인스턴스를 받아서 초기화하는 방식
    public GuestRegist(CheckInUI checkInUI) {
        this.checkInUI = checkInUI; // 전달된 CheckInUI 인스턴스를 초기화
        initComponents();
        setLocationRelativeTo(null);
    }

    private void handleRegister() {
        String name = nameTextField.getText().trim();
        String phone = phoneTextField1.getText().trim() + "-" + phoneTextField2.getText().trim() + "-" + phoneTextField3.getText().trim();
        String roomNumber = roomNumberTextField.getText().trim();
        String stayCost = stayCostTextField.getText().trim();

        if (name.isEmpty() || phone.isEmpty() || roomNumber.isEmpty() || stayCost.isEmpty()) {
            JOptionPane.showMessageDialog(this, "모든 필드를 올바르게 입력해 주세요.", "입력 오류", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            Double.parseDouble(stayCost);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "객실 금액은 숫자로 입력해야 합니다.", "입력 오류", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String reservationId = UUID.randomUUID().toString();
        ReservationData reservation = new ReservationData(reservationId, name, phone, "", "", "", roomNumber, "1", stayCost, "현금", "예약 완료");
        reservationManager.addReservation(reservation);
        JOptionPane.showMessageDialog(this, "손님 등록이 완료되었습니다.", "등록 완료", JOptionPane.INFORMATION_MESSAGE);
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radiobuttonGroup = new javax.swing.ButtonGroup();
        paymentMethodLabel = new javax.swing.JLabel();
        onSitePaymentButton = new javax.swing.JRadioButton();
        cardRegistButton = new javax.swing.JRadioButton();
        registButton = new javax.swing.JButton();
        reservationsubmit = new javax.swing.JButton();
        back = new javax.swing.JButton();
        labelCardStatus = new javax.swing.JLabel();
        paymentType = new javax.swing.JComboBox<>();
        wonLabel = new javax.swing.JLabel();
        phoneTextField3 = new javax.swing.JTextField();
        phoneTextField2 = new javax.swing.JTextField();
        phoneTextField1 = new javax.swing.JTextField();
        stayCostLabel = new javax.swing.JLabel();
        phoneNumberLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        hoLabel = new javax.swing.JLabel();
        roomNumberTextField = new javax.swing.JTextField();
        roomNumberLabel = new javax.swing.JLabel();
        stayCostTextField = new javax.swing.JTextField();
        checkInDateLabel = new javax.swing.JLabel();
        checkOutDateLabel = new javax.swing.JLabel();
        checkOutDateTextField = new javax.swing.JTextField();
        checkInDateTextField = new javax.swing.JTextField();
        guestCountLabel = new javax.swing.JLabel();
        guestCountTextField = new javax.swing.JTextField();
        meongLabel = new javax.swing.JLabel();
        guestPlusButton = new javax.swing.JButton();
        calendar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        paymentMethodLabel.setText("결제수단");

        radiobuttonGroup.add(onSitePaymentButton);
        onSitePaymentButton.setText("현장결제");
        onSitePaymentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onSitePaymentButtonActionPerformed(evt);
            }
        });

        radiobuttonGroup.add(cardRegistButton);
        cardRegistButton.setSelected(true);
        cardRegistButton.setText("카드등록");
        cardRegistButton.setToolTipText("");
        cardRegistButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardRegistButtonActionPerformed(evt);
            }
        });

        registButton.setText("등록");
        registButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registButtonActionPerformed(evt);
            }
        });

        reservationsubmit.setText("저장");
        reservationsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservationsubmitActionPerformed(evt);
            }
        });

        back.setText("뒤로");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        labelCardStatus.setText("등록완료");
        labelCardStatus.setVisible(false);

        paymentType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "현금", "카드" }));
        paymentType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentTypeActionPerformed(evt);
            }
        });

        wonLabel.setText("원");

        phoneTextField1.setText("010");

        stayCostLabel.setText("객실 금액");

        phoneNumberLabel.setText("전화 번호");

        nameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameTextFieldFocusLost(evt);
            }
        });

        nameLabel.setText("이름");
        nameLabel.setToolTipText("");

        hoLabel.setText("호");

        roomNumberTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roomNumberTextFieldMouseClicked(evt);
            }
        });
        roomNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomNumberTextFieldActionPerformed(evt);
            }
        });

        roomNumberLabel.setText("방 번호");

        stayCostTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stayCostTextFieldMouseClicked(evt);
            }
        });
        stayCostTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stayCostTextFieldActionPerformed(evt);
            }
        });

        checkInDateLabel.setText("예상 체크인 날짜");

        checkOutDateLabel.setText("예상 체크아웃 날짜");

        checkOutDateTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkOutDateTextFieldMouseClicked(evt);
            }
        });
        checkOutDateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutDateTextFieldActionPerformed(evt);
            }
        });

        checkInDateTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkInDateTextFieldMouseClicked(evt);
            }
        });
        checkInDateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInDateTextFieldActionPerformed(evt);
            }
        });

        guestCountLabel.setText("인원수");

        guestCountTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guestCountTextFieldMouseClicked(evt);
            }
        });
        guestCountTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guestCountTextFieldActionPerformed(evt);
            }
        });

        meongLabel.setText("명");

        guestPlusButton.setText("인원 추가");
        guestPlusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guestPlusButtonActionPerformed(evt);
            }
        });

        calendar.setText("☎");
        calendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(reservationsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkOutDateLabel)
                                    .addComponent(checkInDateLabel)
                                    .addComponent(roomNumberLabel)
                                    .addComponent(phoneNumberLabel)
                                    .addComponent(nameLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(roomNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(hoLabel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(nameTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(phoneTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(phoneTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(phoneTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(stayCostTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(wonLabel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(guestCountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(meongLabel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(checkOutDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(checkInDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(calendar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(151, 151, 151)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(stayCostLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(guestCountLabel)
                                    .addComponent(paymentMethodLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(onSitePaymentButton)
                                .addGap(7, 7, 7)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(paymentType, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cardRegistButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(registButton)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(guestPlusButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelCardStatus)
                                .addGap(17, 17, 17))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLabel)
                            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phoneNumberLabel)
                            .addComponent(phoneTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkInDateLabel)
                            .addComponent(checkInDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(calendar))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkOutDateLabel)
                            .addComponent(checkOutDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(roomNumberLabel)
                            .addComponent(roomNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hoLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stayCostLabel)
                            .addComponent(stayCostTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wonLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(guestPlusButton)
                            .addComponent(guestCountLabel)
                            .addComponent(guestCountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(meongLabel))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelCardStatus)
                        .addGap(6, 6, 6)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paymentMethodLabel)
                    .addComponent(onSitePaymentButton)
                    .addComponent(paymentType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardRegistButton)
                    .addComponent(registButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back)
                    .addComponent(reservationsubmit))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onSitePaymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onSitePaymentButtonActionPerformed
        labelCardStatus.setVisible(false);
    }//GEN-LAST:event_onSitePaymentButtonActionPerformed

    private void cardRegistButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardRegistButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardRegistButtonActionPerformed

    private void registButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registButtonActionPerformed
        // CardRegistFrame 인스턴스를 생성하여 카드 등록 창을 표시
        CardRegistFrame cardRegistFrame = new CardRegistFrame();
        cardRegistFrame.setLocationRelativeTo(this);  // 현재 GuestRegist 창을 기준으로 중앙에 배치
        cardRegistFrame.setVisible(true);
    }//GEN-LAST:event_registButtonActionPerformed

    private void reservationsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservationsubmitActionPerformed
        // 텍스트 필드에 있는 정보들을 모두 가져오기
        String name = nameTextField.getText().trim();
        String phone = phoneTextField1.getText().trim() + "-" + phoneTextField2.getText().trim() + "-" + phoneTextField3.getText().trim();
        String address = ""; // 예시로 address 필드가 추가된 경우, 입력된 텍스트가 필요하다면 addressTextField.getText().trim() 등으로 가져옵니다.
        String roomNumber = roomNumberTextField.getText().trim();
        String checkInDate = checkInDateTextField.getText().trim();
        String checkOutDate = checkOutDateTextField.getText().trim();
        String guestCount = guestCountTextField.getText().trim();
        String stayCost = stayCostTextField.getText().trim();
        String paymentMethod = paymentType.getSelectedItem().toString();
        String status = "예약 완료"; // 초기 예약 상태는 "예약 완료"로 설정

        // 필드에 하나라도 비어 있는 항목이 있는 경우 오류 메시지 표시
        if (name.isEmpty() || phone.isEmpty() || roomNumber.isEmpty() || checkInDate.isEmpty() || checkOutDate.isEmpty() || guestCount.isEmpty() || stayCost.isEmpty()) {
            JOptionPane.showMessageDialog(this, "모든 필드를 올바르게 입력해 주세요.", "입력 오류", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 새 예약 정보 생성
        ReservationData newReservation = new ReservationData(
                UUID.randomUUID().toString(), // 고유 번호 생성
                name,
                address,
                phone,
                checkInDate,
                checkOutDate,
                roomNumber,
                guestCount,
                stayCost,
                paymentMethod,
                status
        );

        // 파일에 예약 정보 저장
        ReservationManager reservationManager = new ReservationManager();
        reservationManager.addReservation(newReservation);

        // 테이블에 새 예약 정보 추가
        if (checkInUI != null) {
            checkInUI.addReservationToTable(newReservation);
        }

        JOptionPane.showMessageDialog(this, "예약이 완료되었습니다.", "예약 완료", JOptionPane.INFORMATION_MESSAGE);

        // 텍스트 필드 초기화
        nameTextField.setText("");
        phoneTextField1.setText("010");
        phoneTextField2.setText("");
        phoneTextField3.setText("");
        roomNumberTextField.setText("");
        checkInDateTextField.setText("");
        checkOutDateTextField.setText("");
        guestCountTextField.setText("");
        stayCostTextField.setText("");
    }//GEN-LAST:event_reservationsubmitActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        this.dispose(); // 창을 닫음
    }//GEN-LAST:event_backActionPerformed

    private void paymentTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paymentTypeActionPerformed

    private void nameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTextFieldFocusGained

    }//GEN-LAST:event_nameTextFieldFocusGained

    private void nameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTextFieldFocusLost

    }//GEN-LAST:event_nameTextFieldFocusLost

    private void roomNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomNumberTextFieldActionPerformed

    private void roomNumberTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomNumberTextFieldMouseClicked

    }//GEN-LAST:event_roomNumberTextFieldMouseClicked

    private void stayCostTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stayCostTextFieldMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_stayCostTextFieldMouseClicked

    private void stayCostTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stayCostTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stayCostTextFieldActionPerformed

    private void checkOutDateTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkOutDateTextFieldMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_checkOutDateTextFieldMouseClicked

    private void checkOutDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutDateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkOutDateTextFieldActionPerformed

    private void checkInDateTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkInDateTextFieldMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_checkInDateTextFieldMouseClicked

    private void checkInDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInDateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkInDateTextFieldActionPerformed

    private void guestCountTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guestCountTextFieldMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_guestCountTextFieldMouseClicked

    private void guestCountTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guestCountTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guestCountTextFieldActionPerformed

    private void guestPlusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guestPlusButtonActionPerformed
        try {
            int currentCost = Integer.parseInt(stayCostTextField.getText().trim());
            currentCost += 20000;
            stayCostTextField.setText(String.valueOf(currentCost));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "객실 금액이 올바르지 않습니다.", "입력 오류", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_guestPlusButtonActionPerformed

    private void calendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarActionPerformed
        HotelRoomReservationUI hotelRoomReservationUI = new HotelRoomReservationUI();
        hotelRoomReservationUI.showUI();
    }//GEN-LAST:event_calendarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton calendar;
    private javax.swing.JRadioButton cardRegistButton;
    private javax.swing.JLabel checkInDateLabel;
    private javax.swing.JTextField checkInDateTextField;
    private javax.swing.JLabel checkOutDateLabel;
    private javax.swing.JTextField checkOutDateTextField;
    private javax.swing.JLabel guestCountLabel;
    private javax.swing.JTextField guestCountTextField;
    private javax.swing.JButton guestPlusButton;
    private javax.swing.JLabel hoLabel;
    private javax.swing.JLabel labelCardStatus;
    private javax.swing.JLabel meongLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JRadioButton onSitePaymentButton;
    private javax.swing.JLabel paymentMethodLabel;
    private javax.swing.JComboBox<String> paymentType;
    private javax.swing.JLabel phoneNumberLabel;
    private javax.swing.JTextField phoneTextField1;
    private javax.swing.JTextField phoneTextField2;
    private javax.swing.JTextField phoneTextField3;
    private javax.swing.ButtonGroup radiobuttonGroup;
    private javax.swing.JButton registButton;
    private javax.swing.JButton reservationsubmit;
    private javax.swing.JLabel roomNumberLabel;
    private javax.swing.JTextField roomNumberTextField;
    private javax.swing.JLabel stayCostLabel;
    private javax.swing.JTextField stayCostTextField;
    private javax.swing.JLabel wonLabel;
    // End of variables declaration//GEN-END:variables
}
